### ISSUE TITLE
Some Variables and Methods Don't Have a Proper C# Naming Convention

### ISSUE THREAD

**Issue by dbelokon** [hphan9/shinny-ssg#1]
1. Public Methods: I have noticed that you were using camel casing (likeThis) for public methods. While it is correct for most of the other programming languages, it is not the case for C#.  Instead, it is better to use correct naming conventions since it will help you and other contributors to maintain your code easily. In C#, you would want to use parsal casing (LikeThis).

   For example, the getPage method in your Page.cs file can be changed from this

      `public string getPage() { //... }`

     to this

      `public string GetPage() { //... }`

2. Private Variables: private variables should follow camel casing (likeThis) with an underscore at the beginning (_somethingLikeThis). 

   So you would want to change your private variables from this
    
      `private string cssString;`
    
      to this
    
      `private string _cssString;`

3. I think that you forgot to put "const" in here(Program.cs, line 12), because you capitalized the whole name, I thought you meant it to be a constant:

   `string DESTINATION = @".\dist";`

I recommend you to go through your code and do a bit of refactoring. I found [this](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) documentation on C# naming conventions to be very useful. You can check it out.

**Comment by hphan9** [comment]
Thank  you I will fix it
