### ISSUE TITLE
Generated HTML Files Don't Follow Correct Markup

### ISSUE THREAD

**Issue by dbelokon** [hphan9/shinny-ssg#2]
# Bug: 

When I tested the generated HTML files using https://html5.validator.nu/, the following errors were displayed:

![image](https://user-images.githubusercontent.com/67607236/133652126-1e66e887-d646-4fde-8662-8df06e22d9e7.png)

When I pasted the generated HTML into the HTML formatter, I noticed that you have 2 `<head></head>` elements and that the `<!DOCTYPE html>` is missing.  See below:

![image](https://user-images.githubusercontent.com/67607236/133653355-706e874f-a406-4f0d-b3ad-35bc9832291c.png)

# Solution:

I recommend you to go through the minimal requirements for the HTML Markup and add the missing elements/remove duplicate elements  in your code where you generate the HTML pages: 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
  </head>
  <body>
    <!-- page content -->
  </body>
</html>
```

**Comment by hphan9** [comment]
I found the bug , thank you so much

**Comment by dbelokon** [comment]
Any time!! 😄
