### ISSUE TITLE
README.md: Recommendations and Typos

### ISSUE THREAD

**Issue by dbelokon** [hphan9/shinny-ssg#3]
# Recommendations: 

- Installation Instructions: try to include the installation instructions, so it makes it easier for other people to know what needs to be done in order to install your project before using it.
- Examples: including examples on how to use your program would be a great addition. For instance, imagine someone wants to add a stylesheet for the HTML  page to be generated using your program, how would one do it? What commands would someone have to enter? What would be the input and output? Does the order of the commands entered matters? Describe the flow. I think this will help a lot to understand how to use your program easily😁
- Author: I think that it is optional, but you can add the info about who the author is, like your name, if you want to. 
- Dist folder: just a nitpick, but it took a while to find the dist folder. I suggest to either mention where to find it in the README.md file or create it somewhere less nested. For example, instead of placing it here: folder1/folder2/folder3/dist, place it in here folder1/dist.  You can also display the full path of the dist folder to the user.

# Grammar, Spelling, Typos, etc:

1. ![image](https://user-images.githubusercontent.com/67607236/133657971-690c8ce0-5901-4101-abc2-6acfa327ef51.png)

missing a word between .html and .txt, can be fixed to this:

>generate a .html file from a .txt file with a title

2. ![image](https://user-images.githubusercontent.com/67607236/133658840-12fc462c-c824-4416-9f73-43e10fec61ab.png)

A small typo in there ^

>"origional" should be changed to "original"

3. ![image](https://user-images.githubusercontent.com/67607236/133659072-ebd7bd53-2eaa-4eca-80c1-a3da30d7e0c8.png)

Some grammar issues. Change to this:

>give user the option to choose a destination folder and a stylesheet link

**Comment by hphan9** [comment]
great recommendation
